package org.hero.tools;

import com.google.gson.annotations.SerializedName;

import java.util.*;

/**
 * contains tools-related records
 */
public class ToolsInformation {

    /**
     *
     * @param type     this is always "function", don't pass it
     * @param function
     */
    public record ToolData(String type, Function function) {
        public ToolData(Function function) {
            this("function", function);
        }
    }

    /**
     *
     * @param type       this is always "object", don't pass it
     * @param properties
     * @param required
     */
    public record Parameters(String type, Map<String, Property> properties, List<String> required) {
        public Parameters(Map<String, Property> properties, List<String> required) {
            this("object", properties, required);
        }
    }

    public record Function(String name, String description, Parameters parameters) {
    }

    /**
     *
     * @param type        the type of parameters the AI will use (string, int, boolean, etc.)
     * @param description
     */
    public record Property(PropertiesType type, String description) {
    }

    /**
     * a single tool invocation requested by the model
     *
     * @param id       identifier of this call, generated by Ollama
     * @param function the function the model wants to run
     */
    public record ToolCall(String id, FunctionCall function) {
    }

    /**
     * the function part of a {@link ToolCall}
     *
     * @param index     position of this call when the model requests several in one reply
     * @param name      name of the tool to run, matches {@link Function#name()}
     * @param arguments arguments chosen by the model, keyed by parameter name. Values are
     *                  whatever Gson parsed (numbers come back as {@link Double}),
     *                  so check types before casting
     */
    public record FunctionCall(int index, String name, Map<String, Object> arguments) {
    }

    public static class ToolDataBuilder {

        private Function function;
        private Parameters parameters;
        private final Map<String, Property> properties = new HashMap<>();
        private final List<String> required = new ArrayList<>();


        /**
         * use {@link builder}
         */
        private ToolDataBuilder() {
        }


        public static ToolDataBuilder builder() {
            return new ToolDataBuilder();
        }


        public ToolDataBuilder parameter(String argumentName, PropertiesType type, String description, boolean isRequired) {
            properties.put(Objects.requireNonNull(argumentName, "argumentName must not be null"),
                    new Property(
                            Objects.requireNonNull(type, "type must not be null"),
                            Objects.requireNonNull(description, "description must not be null")
                    ));
            if (isRequired) {
                required.add(argumentName);
            }
            return this;
        }


        public ToolDataBuilder buildParameters() {
            parameters = new Parameters(properties, required);
            return this;
        }

        public ToolDataBuilder function(String name, String description) {
            if (this.parameters == null) throw new IllegalStateException("parameters have not been built yet");
            this.function = new Function(
                    Objects.requireNonNull(name, "name must not be null"),
                    Objects.requireNonNull(description, "description must not be null"),
                    parameters);
            return this;
        }

        public ToolData build() {
            if (this.function == null) throw new IllegalStateException("function has not been built yet");
            return new ToolData(function);
        }
    }

    public enum PropertiesType {
        @SerializedName("array") ARRAY,
        @SerializedName("integer") INTEGER,
        @SerializedName("number") NUMBER,
        @SerializedName("object") OBJECT,
        @SerializedName("string") STRING,
        @SerializedName("boolean") BOOLEAN,
        @SerializedName("null") NULL
    }

    /**
     * don't instantiate this
     */
    private ToolsInformation() {
        throw new AssertionError("no org.hero.chatai.ToolsInformation instances for you!");
    }

}
